const EMAIL = 'p.satish9988@gmail.com';
const main = document.querySelector('#main');
const icons = {
 home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',
 workflow:'<rect x="3" y="3" width="6" height="6" rx="1.5"/><rect x="15" y="15" width="6" height="6" rx="1.5"/><path d="M15 6h3v9M9 6h6M6 9v9h9"/>',
 message:'<path d="M21 11a8 8 0 0 1-8 8H8l-5 3V6a3 3 0 0 1 3-3h10a5 5 0 0 1 5 5Z"/><path d="M7 8h10M7 12h7"/>',
 settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',
 spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>',
 user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
 mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
 chart:'<path d="M4 3v17h17M8 15v-4M13 15V6M18 15V9"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 link:'<path d="m9 15 6-6M7 14l-2 2a4 4 0 0 0 6 5l4-4M17 10l2-2a4 4 0 0 0-6-5L9 7"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 file:'<path d="M14 2H5v20h14V7Z M14 2v6h5M8 13h8M8 17h6"/>',
 shield:'<path d="m12 2 8 4v6c0 6-8 10-8 10S4 18 4 12V6Z"/><path d="m8 12 3 3 5-6"/>'
};
const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.workflow}</svg>`;
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const services = [
 {name:'Lead management',category:'SALES & CRM',icon:'workflow',color:'',text:'Capture enquiries, organise your leads, and keep every follow-up moving.'},
 {name:'Email automation',category:'COMMUNICATION',icon:'mail',color:'blue',text:'Create timely email workflows for onboarding, reminders, and client updates.'},
 {name:'Reports & insights',category:'DATA & REPORTING',icon:'chart',color:'orange',text:'Bring your data together and turn routine reporting into a repeatable process.'},
 {name:'App integrations',category:'CONNECTED TOOLS',icon:'link',color:'green',text:'Connect the tools you already use and reduce duplicate data entry.'},
 {name:'Task coordination',category:'OPERATIONS',icon:'clock',color:'pink',text:'Route tasks to the right person and keep recurring work on schedule.'},
 {name:'Document workflows',category:'ADMINISTRATION',icon:'file',color:'slate',text:'Streamline document preparation, approvals, and organised handovers.'}
];
let backend = false;
let user = null;
let toastTimer;
let prefs = {theme:'light',compact:false,motion:false};
try { prefs = {...prefs,...JSON.parse(localStorage.getItem('stratarix-preferences') || '{}')}; } catch {}
function applyPrefs(){document.body.dataset.theme = prefs.theme;document.body.classList.toggle('compact',prefs.compact);document.body.classList.toggle('reduced-motion',prefs.motion);}
applyPrefs();
function hydrate(){document.querySelectorAll('[data-icon]').forEach(el => el.innerHTML=icon(el.dataset.icon));}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,4500);}
function closeMenu(){document.querySelector('#sidebar').classList.remove('open');document.querySelector('#menu-overlay').hidden=true;document.querySelector('#menu-button').setAttribute('aria-expanded','false');}
document.querySelector('#menu-button').addEventListener('click',()=>{const open=document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#menu-overlay').hidden=!open;document.querySelector('#menu-button').setAttribute('aria-expanded',String(open));});
document.querySelector('#menu-overlay').addEventListener('click',closeMenu);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
document.querySelector('#year').textContent=new Date().getFullYear();
function updateAccount(){document.querySelector('#account-name').textContent=user?.name || 'Your workspace';document.querySelector('#account-detail').textContent=user?(user.demo?'Preview account':'Account settings'):'Log in to get started';document.querySelector('#account-link').href=user?'#settings':'#login';document.querySelector('#header-login').textContent=user?'Settings':'Log in';document.querySelector('#header-login').href=user?'#settings':'#login';const action=document.querySelector('#header-register');action.textContent=user?'Contact us ↗':'Create account ↗';action.href=user?'#contact':'#register';}
function intro(title,copy){return `<div class="intro"><div><h1>${title}</h1><p>${copy}</p></div></div>`;}
function serviceCard(s){return `<article class="service"><div class="service-top"><span class="service-icon ${s.color}">${icon(s.icon)}</span><span class="example">EXAMPLE</span></div><h3>${s.name}</h3><p>${s.text}</p><div class="service-bottom"><span>${s.category}</span><a href="#contact?service=${encodeURIComponent(s.name)}" aria-label="Enquire about ${s.name}">Enquire ↗</a></div></article>`;}
function home(){return `${intro(user?`Welcome, ${esc(user.name.split(' ')[0])}.`:'Make room for better work.','Explore practical automations for your everyday business processes.')}<section class="hero"><div><span class="eyebrow">BUILT AROUND YOUR WORK</span><h2>Your tools, connected.<br>Your work, <em>simplified.</em></h2><p>From the first enquiry to the final follow-up, bring your repetitive tasks into one thoughtful workflow.</p><a class="button light" href="#contact">Let’s talk automation <span aria-hidden="true">↗</span></a></div><div class="workflow" aria-label="Example workflow: enquiry received, lead organised, follow-up prepared"><div class="workflow-title"><span>One enquiry. A connected process.</span><span>EXAMPLE</span></div><div class="flow-step"><span class="flow-icon">${icon('message')}</span><div><strong>New enquiry received</strong><small>Website contact form</small></div><span class="check">${icon('check')}</span></div><div class="flow-connector"></div><div class="flow-step"><span class="flow-icon">${icon('workflow')}</span><div><strong>Lead organised</strong><small>Details added to your CRM</small></div><span class="check">${icon('check')}</span></div><div class="flow-connector"></div><div class="flow-step"><span class="flow-icon">${icon('mail')}</span><div><strong>Follow-up prepared</strong><small>A timely next step for your team</small></div><span class="check">${icon('check')}</span></div><div class="flow-end">${icon('link')} A sample workflow, tailored to your tools.</div></div></section><section><div class="section-heading"><div><h2>A starting point for your next workflow</h2><p>Example services. Built to fit your requirements.</p></div><a class="text-link" href="#services">View all ↗</a></div><div class="services-grid">${services.slice(0,3).map(serviceCard).join('')}</div></section><section class="next-step"><span class="next-icon">${icon('message')}</span><div><h3>Not sure where to start?</h3><p>Tell us what takes up your time. We’ll discuss what could be automated.</p></div><a class="button secondary" href="#contact">Start a conversation ↗</a></section>`;}
function contact(){return `${intro('Let’s simplify your workflow.','Share your requirements and start a conversation with Stratarix.')}<div class="page-grid"><section class="panel contact-info"><span class="eyebrow">CONTACT US</span>${icon('message')}<h2>Good automation starts with a conversation.</h2><p>Tell us about your process, your tools, and the result you want to achieve.</p><a class="contact-email" href="mailto:${EMAIL}">${EMAIL} ↗</a><div class="button-row"><a class="button light" href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;to=${EMAIL}" target="_blank" rel="noopener noreferrer">Contact with Gmail ↗</a><button class="button secondary" id="copy-email">Copy email</button></div><hr><h3>What to include</h3><ul><li>The task you want to automate</li><li>The apps your team uses</li><li>Your preferred timeline and budget</li></ul><p class="form-note">We’ll discuss scope and availability before confirming a project.</p></section><section class="panel"><h2>Tell us about your project</h2><p>A few details will help us understand your needs.</p><form id="contact-form"><div class="form-row"><div class="field"><label for="contact-name">Your name</label><input id="contact-name" name="name" placeholder="Full name" value="${esc(user?.demo?'':user?.name || '')}" required maxlength="80" autocomplete="name"></div><div class="field"><label for="contact-email">Email address</label><input id="contact-email" name="email" type="email" placeholder="you@company.com" value="${esc(user?.demo?'':user?.email || '')}" required maxlength="254" autocomplete="email"></div></div><div class="field"><label for="contact-service">What would you like to automate?</label><select id="contact-service" name="service"><option>Custom automation</option>${services.map(s=>`<option>${s.name}</option>`).join('')}</select></div><div class="field"><label for="contact-message">Project details</label><textarea id="contact-message" name="message" placeholder="Describe your current process and what you would like to improve…" required minlength="10" maxlength="3000"></textarea></div><button class="button full" type="submit">Prepare email ↗</button><p class="form-note">Opens your email app with your enquiry. Review and send it there. This form does not send or store your message.</p><p id="contact-result" class="form-message success" role="status" hidden></p></form></section></div>`;}
function auth(register){if(user)return `${intro('Your workspace is ready.','You are signed in.')}<section class="panel account-panel"><span class="service-icon">${icon('user')}</span><h2>Welcome, ${esc(user.name)}</h2><p>${user.demo?'You’re exploring the preview. No real account has been created.':esc(user.email)}</p><div class="button-row"><a class="button" href="#settings">Account settings</a><button id="logout" class="button secondary">Log out</button></div></section>`;return `<div class="auth-layout"><section class="auth-story"><span class="eyebrow">YOUR STRATARIX WORKSPACE</span><h2>Less repetition.<br><span>More room<br>to move forward.</span></h2><p>A simple place to connect with our team and take the next step in your automation project.</p><div class="auth-points"><div>${icon('workflow')} Explore automation possibilities</div><div>${icon('message')} Discuss your requirements</div><div>${icon('settings')} Manage your preferences</div></div></section><section class="auth-form"><h1>${register?'Create your account':'Welcome back'}</h1><p>${register?'Get started with your Stratarix workspace.':'Log in to your Stratarix workspace.'}</p>${!backend?'<div class="demo-notice"><strong>Website preview</strong><br>Account registration and login require the included server. You can explore this preview without entering a password.</div>':''}<form id="auth-form">${register?'<div class="field"><label for="auth-name">Full name</label><input id="auth-name" name="name" required minlength="2" maxlength="80" autocomplete="name" placeholder="Your full name" '+(!backend?'disabled':'')+'></div>':''}<div class="field"><label for="auth-email">Email address</label><input id="auth-email" name="email" type="email" required maxlength="254" autocomplete="email" placeholder="you@company.com" ${!backend?'disabled':''}></div><div class="field"><label for="auth-password">Password</label><input id="auth-password" name="password" type="password" required minlength="12" maxlength="128" autocomplete="${register?'new-password':'current-password'}" placeholder="${register?'At least 12 characters':'Enter your password'}" ${!backend?'disabled':''}>${register?'<small>Use 12 or more characters. Do not reuse another account’s password.</small>':''}</div><p class="form-message" id="auth-error" role="alert" hidden></p><button class="button full" type="submit" ${!backend?'disabled':''}>${register?'Create account':'Log in'} ↗</button></form>${!backend?'<button id="demo-login" class="button secondary full demo-button">Explore demo workspace</button>':''}<p class="alternate">${register?'Already have an account? <a href="#login">Log in</a>':'New to Stratarix? <a href="#register">Create an account</a>'}</p></section></div>`;}
function settings(){return `${intro('Your workspace, your way.','Manage your profile and choose how you like to work.')}<div class="settings-layout"><section class="panel"><h2>Profile</h2>${user?`<p>${user.demo?'Preview account · Changes apply to this session only.':esc(user.email)}</p><form id="profile-form"><div class="field"><label for="profile-name">Display name</label><input id="profile-name" name="name" minlength="2" maxlength="80" required value="${esc(user.name)}" autocomplete="name"></div><p id="profile-error" class="form-message" role="alert" hidden></p><div class="button-row"><button class="button" type="submit">Save profile</button><button class="button secondary" type="button" id="logout">Log out</button></div></form>`:'<p>Log in to manage your profile, or create an account to get started.</p><div class="button-row"><a class="button" href="#login">Log in</a><a class="button secondary" href="#register">Create account</a></div>'}</section><section class="panel"><h2>Appearance</h2><p>These preferences are saved on this browser.</p><div class="setting-row"><div><label for="theme">Colour theme</label><p>Choose a comfortable viewing experience.</p></div><select id="theme"><option value="light" ${prefs.theme==='light'?'selected':''}>Light</option><option value="dark" ${prefs.theme==='dark'?'selected':''}>Dark</option></select></div><div class="setting-row"><div><label for="compact">Compact layout</label><p>Use less space between service content.</p></div><input type="checkbox" id="compact" ${prefs.compact?'checked':''}></div><div class="setting-row"><div><label for="motion">Reduce motion</label><p>Turn off interface transitions.</p></div><input type="checkbox" id="motion" ${prefs.motion?'checked':''}></div></section><section class="panel"><h2>Need a hand?</h2><p>Contact us about your account or your next automation project.</p><a class="text-link" href="#contact">Contact Stratarix ↗</a></section></div>`;}
async function api(path,body){const res=await fetch(`./api/${path}`,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json','X-Stratarix-Request':'1'}:{},body:body?JSON.stringify(body):undefined});let data;try{data=await res.json();}catch{throw new Error('The account server is unavailable. Please try again later.');}if(!res.ok)throw new Error(data.error||'Unable to complete your request.');return data;}
function attach(){
 const copy=document.querySelector('#copy-email');if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(EMAIL);toast('Email address copied.');}catch{toast(`Email us at ${EMAIL}`);}};
 const contactForm=document.querySelector('#contact-form');if(contactForm){const service=new URLSearchParams(location.hash.split('?')[1]||'').get('service');if(services.some(s=>s.name===service))contactForm.elements.service.value=service;contactForm.onsubmit=e=>{e.preventDefault();const f=new FormData(contactForm);const subject=`Automation enquiry — ${f.get('service')}`;const body=`Hello Stratarix,\n\nName: ${f.get('name')}\nEmail: ${f.get('email')}\nService: ${f.get('service')}\n\n${f.get('message')}\n\nRegards,\n${f.get('name')}`;location.href=`mailto:${EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;const result=document.querySelector('#contact-result');result.textContent='Your email draft is ready. If your email app did not open, use Contact with Gmail or copy the email address. Nothing has been sent yet.';result.hidden=false;};}
 const authForm=document.querySelector('#auth-form');if(authForm)authForm.onsubmit=async e=>{e.preventDefault();if(!backend)return;const btn=authForm.querySelector('button[type=submit]');const error=document.querySelector('#auth-error');btn.disabled=true;error.hidden=true;try{user=(await api(location.hash.startsWith('#register')?'register':'login',Object.fromEntries(new FormData(authForm)))).user;updateAccount();location.hash='home';toast('You are signed in.');}catch(err){error.textContent=err.message;error.hidden=false;}finally{btn.disabled=false;}};
 const demo=document.querySelector('#demo-login');if(demo)demo.onclick=()=>{user={name:'Demo client',email:'',demo:true};updateAccount();location.hash='home';toast('Demo workspace opened. No account has been created.');};
 const logout=document.querySelector('#logout');if(logout)logout.onclick=async()=>{try{if(backend&&!user?.demo)await api('logout',{});user=null;updateAccount();location.hash='login';toast('You are logged out.');}catch(err){toast(err.message);}};
 const profile=document.querySelector('#profile-form');if(profile)profile.onsubmit=async e=>{e.preventDefault();const name=profile.elements.name.value.trim();const btn=profile.querySelector('button[type=submit]');const error=document.querySelector('#profile-error');btn.disabled=true;error.hidden=true;try{if(name.length<2)throw new Error('Enter at least two characters.');if(user.demo)user.name=name;else user=(await api('profile',{name})).user;updateAccount();toast('Profile saved.');}catch(err){error.textContent=err.message;error.hidden=false;}finally{btn.disabled=false;}};
 ['theme','compact','motion'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener('change',()=>{prefs[id]=id==='theme'?el.value:el.checked;applyPrefs();try{localStorage.setItem('stratarix-preferences',JSON.stringify(prefs));toast('Preference saved.');}catch{toast('Preference applied. Your browser could not save it.');}});});
}
function render(){const page=(location.hash.slice(1).split('?')[0]||'home');const pages={home:['Overview',home],services:['Automations',()=>`${intro('Built around the way you work.','Explore example automation services. Scope and pricing are agreed after discussing your requirements.')}<div class="services-grid">${services.map(serviceCard).join('')}</div><div class="demo-notice">These are temporary service examples. No third-party apps are connected and no automations run from this preview.</div>`],contact:['Contact us',contact],login:['Log in',()=>auth(false)],register:['Create account',()=>auth(true)],settings:['Settings',settings]};const selected=pages[page]||pages.home;main.innerHTML=selected[1]();document.title=`${selected[0]} · Stratarix Automation`;document.querySelector('#page-label').textContent=selected[0];document.querySelectorAll('nav a').forEach(a=>{const active=a.dataset.page===(pages[page]?page:'home');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});hydrate();attach();closeMenu();window.scrollTo(0,0);}
window.addEventListener('hashchange',()=>{render();main.focus({preventScroll:true});});
render();
(async()=>{try{const conf=await api('config');backend=conf.authentication===true;if(backend)user=(await api('me')).user;}catch{backend=false;}updateAccount();if(['login','register','settings'].includes(location.hash.slice(1)))render();})();
